export const rows = [
  {
    id: 1,
    Name: "Ferrara Clifford",
    Email: "ferrara.clifford@net.com",
    age: 44,
    Phone: "01143746347",
    Access: "Admin",
  },
  {
    id: 2,
    Name: "Rossini Frances",
    Email: "rossini.frances@net.com",
    age: 36,
    Phone: "01143746347",
    Access: "Admin",
  },
  {
    id: 3,
    Name: "Harvey Roxie",
    Email: "harvey.roxie@net.com",
    age: 65,
    Phone: "01143746347",
    Access: "Admin",
  },
  {
    id: 4,
    Name: "Daenerys Targaryen",
    Email: "daenerys.targaryen@net.com",
    age: null,
    Phone: "01143746347",
    Access: "Manager",
  },
  {
    id: 5,
    Name: "Melisandre",
    Email: "melisandre@net.com",
    age: 150,
    Phone: "01143746347",
    Access: "Manager",
  },
  {
    id: 6,
    Name: "Jon Snow",
    Email: "JonSnow@net.com",
    age: 14,
    Phone: "01143746347",
    Access: "User",
  },
  {
    id: 7,
    Name: "Cersei Lannister",
    Email: "cersei.lannister@net.com",
    age: 31,
    Phone: "01143746347",
    Access: "User",
  },
  {
    id: 8,
    Name: "Jaime Lannister",
    Email: "jaime.lannister@net.com",
    age: 31,
    Phone: "01143746347",
    Access: "User",
  },
  {
    id: 9,
    Name: "Arya Stark",
    Email: "arya.stark@net.com",
    age: 11,
    Phone: "01143746347",
    Access: "User",
  },
];
