export const columns = [
    {
      field: "id",
      headerName: "ID",
      Width: 33,

    },
    {
      field: "RegistrarID",
      headerName: "RegistrarID",
      flex: 1,

    },
    {
      field: "Name",
      headerName: "Name",
      flex: 1,
      cellClassName:"name-column--cell"
    },
    {
      field: "age",
      headerName: "Age",
      type:"number",
      Width: 33,
      align: "left",
      headerAlign: "left",
    },
    {
      field: "Phone",
      headerName: "Phone",
      flex: 1,
    },
    {
      field: "Email",
      headerName: "Email",
      flex: 1,
    },
    {
      field: "Address",
      headerName: "Address",
      flex: 1,
    },
    {
      field: "City",
      headerName: "City",
      flex: 1,
    },
    {
      field: "ZipCode",
      headerName: "ZipCode",
      flex: 1,
      type:"number",
      align: "left",
      headerAlign: "left",
    },

  ];
export const rows = [
  {
    id: 1,
    RegistrarID: "RG-10428",
    Name: "Ferrara Clifford",
    age: 44,
    Phone: "+1 (312) 459-7731",
    Email: "ferrara.clifford@net.com",
    Address: "1428 Willow Street",
    City: "Chicago",
    ZipCode: "60622",
  },
  {
    id: 2,
    RegistrarID: "RG-87654",
    Name: "Rossini Frances",
    age: 36,
    Phone: "+1 (917) 321-5547",
    Email: "rossini.frances@net.com",
    Address: "57 East 9th Avenue",
    City: "New York",
    ZipCode: "10011",
  },
  {
    id: 3,
    RegistrarID: "RG-72890",
    Name: "Harvey Roxie",
    Email: "harvey.roxie@net.com",
    age: 65,
    Phone: "+61 2 9555 7488",
    Address: "9 Darling Street",
    City: "Sydney",
    ZipCode: "2000",
  },
  {
    id: 4,
    RegistrarID: "RG-76812",
    Name: "Daenerys Targaryen",
    Email: "daenerys.targaryen@net.com",
    age: 31,
    Phone: "+33 1 4030 1142",
    Address: "85 Rue de Rivoli",
    City: "Paris",
    ZipCode: "75004",
  },
  {
    id: 5,
    RegistrarID: "RG-58201",
    Name: "Melisandre",
    Email: "melisandre@net.com",
    age: 150,
    Phone: "+39 06 7842 3331",
    Address: "10 Via Veneto",
    City: "Rome",
    ZipCode: "00187",
  },
  {
    id: 6,
    RegistrarID: "RG-99123",
    Name: "Jon Snow",
    Email: "jonsnow@net.com",
    age: 14,
    Phone: "+1 (415) 682-9090",
    Address: "720 Castro Street",
    City: "San Francisco",
    ZipCode: "94114",
  },
  {
    id: 7,
    RegistrarID: "RG-23987",
    Name: "Cersei Lannister",
    Email: "cersei.lannister@net.com",
    age: 31,
    Phone: "+44 20 7946 0812",
    Address: "22 Baker Street",
    City: "London",
    ZipCode: "NW1 6XE",
  },
  {
    id: 8,
    RegistrarID: "RG-45109",
    Name: "Jaime Lannister",
    Email: "jaime.lannister@net.com",
    age: 31,
    Phone: "+49 30 2897 6445",
    Address: "11 Lindenstrasse",
    City: "Berlin",
    ZipCode: "10178",
  },
  {
    id: 9,
    RegistrarID: "RG-31044",
    Name: "Arya Stark",
    Email: "arya.stark@net.com",
    age: 11,
    Phone: "+971 4 338 9123",
    Address: "44 Sheikh Zayed Road",
    City: "Dubai",
    ZipCode: "00000",
  },
    {
    id: 10,
    RegistrarID: "RG-55210",
    Name: "Sansa Stark",
    age: 20,
    Phone: "+44 131 555 1122",
    Email: "sansa.stark@net.com",
    Address: "10 Royal Mile",
    City: "Edinburgh",
    ZipCode: "EH1 1YZ",
  },
  {
    id: 11,
    RegistrarID: "RG-66321",
    Name: "Tyrion Lannister",
    age: 39,
    Phone: "+1 (212) 555-0198",
    Email: "tyrion.lannister@net.com",
    Address: "415 Broome Street",
    City: "New York",
    ZipCode: "10013",
  },
  {
    id: 12,
    RegistrarID: "RG-77432",
    Name: "Brienne Tarth",
    age: 34,
    Phone: "+33 1 5550 2211",
    Email: "brienne.tarth@net.com",
    Address: "7 Rue de Turenne",
    City: "Paris",
    ZipCode: "75003",
  },
  {
    id: 13,
    RegistrarID: "RG-88543",
    Name: "Sandor Clegane",
    age: 42,
    Phone: "+49 30 5559 7744",
    Email: "sandor.clegane@net.com",
    Address: "29 Friedrichstrasse",
    City: "Berlin",
    ZipCode: "10117",
  },
  {
    id: 14,
    RegistrarID: "RG-99654",
    Name: "Petyr Baelish",
    age: 41,
    Phone: "+44 20 7000 8899",
    Email: "petyr.baelish@net.com",
    Address: "8 Fleet Street",
    City: "London",
    ZipCode: "EC4Y 1AA",
  },
  {
    id: 15,
    RegistrarID: "RG-12011",
    Name: "Ygritte",
    age: 27,
    Phone: "+353 1 555 9020",
    Email: "ygritte@net.com",
    Address: "3 Grafton Street",
    City: "Dublin",
    ZipCode: "D02",
  },
  {
    id: 16,
    RegistrarID: "RG-13122",
    Name: "Margaery Tyrell",
    age: 29,
    Phone: "+39 06 5550 3344",
    Email: "margaery.tyrell@net.com",
    Address: "24 Piazza Navona",
    City: "Rome",
    ZipCode: "00186",
  },
  {
    id: 17,
    RegistrarID: "RG-14233",
    Name: "Jorah Mormont",
    age: 45,
    Phone: "+34 91 555 6677",
    Email: "jorah.mormont@net.com",
    Address: "11 Gran Via",
    City: "Madrid",
    ZipCode: "28013",
  },
  {
    id: 18,
    RegistrarID: "RG-15344",
    Name: "Bronn",
    age: 40,
    Phone: "+41 22 555 4422",
    Email: "bronn@net.com",
    Address: "5 Rue du Rhône",
    City: "Geneva",
    ZipCode: "1204",
  },
  {
    id: 19,
    RegistrarID: "RG-16455",
    Name: "Samwell Tarly",
    age: 32,
    Phone: "+1 (415) 555-7711",
    Email: "samwell.tarly@net.com",
    Address: "18 Market Street",
    City: "San Francisco",
    ZipCode: "94103",
  },
  {
    id: 20,
    RegistrarID: "RG-17566",
    Name: "Gendry Waters",
    age: 28,
    Phone: "+61 2 5550 8899",
    Email: "gendry.waters@net.com",
    Address: "12 George Street",
    City: "Sydney",
    ZipCode: "2000",
  },
  {
    id: 21,
    RegistrarID: "RG-18677",
    Name: "Theon Greyjoy",
    age: 30,
    Phone: "+47 21 555 3030",
    Email: "theon.greyjoy@net.com",
    Address: "4 Karl Johans gate",
    City: "Oslo",
    ZipCode: "0154",
  },
  {
    id: 22,
    RegistrarID: "RG-19788",
    Name: "Davos Seaworth",
    age: 48,
    Phone: "+44 161 555 4422",
    Email: "davos.seaworth@net.com",
    Address: "6 King Street",
    City: "Manchester",
    ZipCode: "M2 4WU",
  },
  {
    id: 23,
    RegistrarID: "RG-20899",
    Name: "Missandei",
    age: 26,
    Phone: "+971 4 555 2211",
    Email: "missandei@net.com",
    Address: "19 Jumeirah Beach Rd",
    City: "Dubai",
    ZipCode: "00000",
  },
  {
    id: 24,
    RegistrarID: "RG-21910",
    Name: "Grey Worm",
    age: 29,
    Phone: "+31 20 555 7788",
    Email: "grey.worm@net.com",
    Address: "2 Dam Square",
    City: "Amsterdam",
    ZipCode: "1012",
  },
  {
    id: 25,
    RegistrarID: "RG-23021",
    Name: "Eddard Stark",
    age: 43,
    Phone: "+44 113 555 1188",
    Email: "eddard.stark@net.com",
    Address: "14 Briggate",
    City: "Leeds",
    ZipCode: "LS1 6HF",
  },
  {
    id: 26,
    RegistrarID: "RG-24132",
    Name: "Catelyn Stark",
    age: 40,
    Phone: "+44 121 555 9900",
    Email: "catelyn.stark@net.com",
    Address: "33 New Street",
    City: "Birmingham",
    ZipCode: "B2 4DU",
  },
  {
    id: 27,
    RegistrarID: "RG-25243",
    Name: "Stannis Baratheon",
    age: 46,
    Phone: "+352 26 555 1122",
    Email: "stannis.baratheon@net.com",
    Address: "8 Avenue de la Gare",
    City: "Luxembourg",
    ZipCode: "1610",
  },
  {
    id: 28,
    RegistrarID: "RG-26354",
    Name: "Oberyn Martell",
    age: 38,
    Phone: "+34 93 555 3344",
    Email: "oberyn.martell@net.com",
    Address: "15 La Rambla",
    City: "Barcelona",
    ZipCode: "08002",
  },
  {
    id: 29,
    RegistrarID: "RG-27465",
    Name: "Jaqen H’ghar",
    age: 37,
    Phone: "+48 22 555 6622",
    Email: "jaqen.hghar@net.com",
    Address: "21 Krakowskie Przedmieście",
    City: "Warsaw",
    ZipCode: "00-071",
  },
];

